# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\xd7\x01\n\rTokenTransfer\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_address\x18\x02 \x01(\t\x12\x12\n\nto_address\x18\x03 \x01(\t\x12\x10\n\x08token_id\x18\x04 \x01(\t\x12\x18\n\x10transaction_hash\x18\x05 \x01(\t\x12\x14\n\x0c\x62lock_number\x18\x06 \x01(\x04\x12\x11\n\tlog_index\x18\x07 \x01(\x04\x12\x10\n\x08\x63hain_id\x18\x08 \x01(\r\x12\x12\n\nblock_hash\x18\t \x01(\t\x12\x10\n\x08tx_index\x18\n \x01(\r\"L\n\x13GetTransfersRequest\x12\x12\n\nfrom_block\x18\x01 \x01(\x04\x12\x10\n\x08to_block\x18\x02 \x01(\x04\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t2J\n\x10TransfersService\x12\x36\n\x0cGetTransfers\x12\x14.GetTransfersRequest\x1a\x0e.TokenTransfer0\x01\x62\x06proto3')



_TOKENTRANSFER = DESCRIPTOR.message_types_by_name['TokenTransfer']
_GETTRANSFERSREQUEST = DESCRIPTOR.message_types_by_name['GetTransfersRequest']
TokenTransfer = _reflection.GeneratedProtocolMessageType('TokenTransfer', (_message.Message,), {
  'DESCRIPTOR' : _TOKENTRANSFER,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:TokenTransfer)
  })
_sym_db.RegisterMessage(TokenTransfer)

GetTransfersRequest = _reflection.GeneratedProtocolMessageType('GetTransfersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSFERSREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:GetTransfersRequest)
  })
_sym_db.RegisterMessage(GetTransfersRequest)

_TRANSFERSSERVICE = DESCRIPTOR.services_by_name['TransfersService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOKENTRANSFER._serialized_start=18
  _TOKENTRANSFER._serialized_end=233
  _GETTRANSFERSREQUEST._serialized_start=235
  _GETTRANSFERSREQUEST._serialized_end=311
  _TRANSFERSSERVICE._serialized_start=313
  _TRANSFERSSERVICE._serialized_end=387
# @@protoc_insertion_point(module_scope)
